export const Films =[
    {id: 1, name: 'VỆ BINH DẢI NGÂN HÀ 2 (C13)', date: '01/05/2023', type: 'Siêu Anh Hùng, Hành Động', time :'149 phút', img:'assets/images/vebinhdainganha.jpg', info : 'Cho dù vũ trụ này có bao la đến đâu, các Vệ Binh của chúng ta cũng không thể trốn chạy mãi mãi.', clip : 'https://www.youtube.com/embed/SCbtkaJO0Rs'},
    {id: 2, name: 'KHẮC TINH CỦA QUỶ (C18)', date: '10/04/2023', type: 'Kinh Dị', time: '104 phút', img:'assets/images/khac-tinh-cua-quy.jpg', info : 'Lấy cảm hứng từ những hồ sơ có thật của Cha Gabriele Amorth, Trưởng Trừ Tà của Vatican (Russell Crowe, đoạt giải Oscar®), bộ phim "The Pope Exorcist" theo chân Amorth trong cuộc điều tra về vụ quỷ ám kinh hoàng của một cậu bé và dần khám phá ra những bí mật hàng thế kỷ mà Vatican đã cố gắng giấu kín.', clip : 'https://www.youtube.com/embed/pH5JWaPBSFg'},
    {id: 3, name: 'MÈO SIÊU QUẬY Ở VIỆN BẢO TÀNG', date: '28/04/2023', type: 'Hài, Hoạt Hình, Phiêu Lưu', time: '80 phút', img:'assets/images/poster_payoff_cats_in_the_museum.jpg', info : 'Câu chuyện xoay quanh tình bạn của chú mèo Vincent và chú chuột Maurice. Vincent vừa nhận được công việc bảo vệ kiệt tác tranh Mona Lisa trong một viện bảo tàng, còn Maurice lại có niềm đam mê gặm nhấm bức tranh này. Mọi chuyện phức tạp hơn khi có người cũng đang nung nấu ý định cướp lấy tuyệt tác Mona Lisa. Liệu Vincent và đồng đội của mình có thể cứu lấy những kiệt tác của Davinci và bảo vệ danh cho bảo tàng không?', clip : 'https://www.youtube.com/embed/xj4cfU9SHIM'},
    {id: 4, name: 'MA LAI RÚT RUỘT (C18)', date: '28/04/2023', type: 'Kinh Dị', time: '122 phút',img:'assets/images/malairutruot.jpg', info : 'Truyền thuyết Ma Lai rút ruột vang danh Đông Nam Á một lần nữa ứng nghiệm. Khi Ma Lai rung động với chàng trai bị nguyền rủa, mối tình lãng mạn nhưng cũng vô cùng rùng rợn liệu có lối thoát? Cloud (Jayler Krissanapoom) sinh ra với chứng rối loạn di truyền dẫn tới bệnh bạch tạng. Sau nhiều năm sống cô độc vì bị xa lánh, Cloud gặp được một cô gái có tên là Sao (Nink Chanya McClory). Cloud nhanh chóng nảy sinh tình cảm với Sao mà không hề biết rằng, cô gái này mang trong mình một bí mật vô cùng khủng khiếp.', clip : 'https://www.youtube.com/embed/EkJRvcytJPo'},
    {id: 5, name: 'NHỮNG KẺ THAO TÚNG (C18)', date: '12/05/2023', type: 'Bí ẩn, Hành Động, Hồi hộp', time: '93 phút',img:'assets/images/nhungkethaotung.jpg', info : 'Phim theo chân thám tử Daniel Rourke (Ben Affleck) trong hành trình tìm kiếm cô con gái bị mất tích. Anh sớm nhận ra tất cả những chuyện bí ẩn này đều liên quan đến một người đàn ông có sức mạnh thôi miên, bẻ cong thực tại. Với sự hỗ trợ từ nhà ngoại cảm Diana Cruz (Alice Braga), Daniel bắt đầu truy đuổi hắn và phải tìm mọi cách để đưa con gái mình trở về nhà an toàn.', clip : 'https://www.youtube.com/embed/1zNqJrf1Mlg'},
    {id: 6, name: 'PHIM CÚ ÚP RỔ ĐẦU TIÊN (C13)', date: '14/04/2023', type: 'Hài, Hoạt Hình', time: '124 phút', img:'assets/images/the_first_slam_dunk_-_key_visual_1_.jpg', info : 'Bộ phim hoạt hình chuyển thể từ loạt truyện tranh “Slam Dunk” nổi tiếng của Takehiko Inoue, khắc họa quá trình trưởng thành cá nhân của những học sinh trung học cống hiến tuổi trẻ cho bóng rổ. Phim theo chân Ryota Miyagi, hậu vệ của đội bóng rổ trường trung học Shohoku. Anh có một người anh trai, Sota, hơn anh ba tuổi và là người đã truyền cảm hứng cho tình yêu bóng rổ của anh. Ryota và các đồng đội của mình là Hanamichi Sakuragi, Takenori Akagi, Hisashi Mitsui và Kaede Rukawa thách đấu nhà vô địch bóng rổ liên trường, đội bóng rổ trường trung học Sannoh. Tác giả nguyên tác Inoue phụ trách chỉ đạo và viết kịch bản.', clip : 'https://www.youtube.com/embed/kDuiynKxjQU'},
    {id: 7, name: 'ĐẦU GẤU ĐỤNG ĐỘ ĐẦU ĐẤT (C16)', date: '21/04/2023', type: 'Hài, Hành Động', time: '98 phút',img:'assets/images/bear-main-poster-printing.jpg', info : 'Phim Đầu Gấu Đụng Đầu Đất dựa trên câu chuyện thần thoại nổi tiếng tại Hàn Quốc về hai chú gấu sinh đôi hoá thành người sau khi ăn tỏi và ngải cứu trong 100 ngày. Chú gấu ăn tỏi trở thành Na Woong-nam, được một cặp vợ chồng nhà khoa học mang về nuôi nấng, tuy chỉ mới 25 tuổi nhưng lại sở hữu “giao diện” của một ông chú 52 với cái “đầu đất” ngây thơ, hiền lành. Trong khi đó, chú gấu ăn ngải cứu trở thành “đầu gấu” Lee Jeong-hak, được một tên trùm tổ chức tội phạm mang về nuôi và bị lợi dụng như một món “vũ khí” phòng vệ. Trong một tình huống bất đắc dĩ, Na Woong-nam đã trực tiếp đối đầu cùng anh em song sinh Lee Jeong-hak để ngăn chặn một vụ khủng bố virus có tầm lây lan mạnh. Sức mạnh của loài gấu bộc phát sẽ đẩy cuộc đụng độ của cặp gấu song sinh hoá người đi đến hồi kết nào?', clip : 'https://www.youtube.com/embed/2IZLhCSApCk'},
    {id: 8, name: 'FAST & FURIOUS X (C16)', date: '11/05/2023', type: 'Hành Động', time: '141 phút',img:'assets/images/fast-furious-x.jpg', info : 'Dom Toretto và gia đình của anh ấy bị trở thành mục tiêu của người con trai đầy thù hận của ông trùm ma túy Hernan Reyes.', clip : 'https://www.youtube.com/embed/nIXKtldz5Yk'},
    {id: 9, name: 'QUÁI VẬT ĐEN (C16)', date: '12/05/2023', type: 'Hành Động, Hồi hộp', time: '100 phút',img:'assets/images/quaivatden.jpg', info : 'Quái Vật Đen xoay quanh câu chuyện khi kỳ nghỉ bình dị của gia đình Oilman Paul Sturges biến thành cơn ác mộng. Bởi họ đã gặp phải một con cá mập Megalodon hung dữ, không từ bất kỳ khoảnh khắc nào để bảo vệ lãnh thổ của mình. Bị mắc kẹt và tấn công liên tục, Paul và gia đình của mình phải tìm cách để an toàn sống sót trở về bờ trước khi con cá mập khát máu này tấn công lần nữa', clip : 'https://www.youtube.com/embed/DAjHDmR6jec'},
  ];
